# -*- mode: ruby -*-
# vi: set ft=ruby :
RAM = 1024
CPU = 2

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = RAM
    vb.cpus = CPU
  end
end
